### PR TITLE
add ci build for fedora, centos

### PR DESCRIPTION
**Pull request by langston-barrett**
Two things need to happen:
1. @mheese visits travis-ci.org/mheese/journalbeat and clicks "activate"
2. @mheese removes the "deploy" section of `.travis.yml`, downloads the Travis CLI and runs `travis setup releases`, replicating the setup shown here. 

I'm also happy to do any of those things, I would just need write permission to the repo. 

This will automatically test, build, package, and release journalbeat binaries in Fedora and Centos 7 environments.

For the lastest build status on my fork: https://travis-ci.org/asteris-llc/journalbeat/branches

### CODE REVIEW

**Comment by mheese** [comment]
pretty awesome! 👍 ... I like it!

I'm curious, is the change of the main.go and changing the name and version to consts relevant to the packaging?

I will test this later today in the afternoon. Thanks for the contribution!

**Comment by langston-barrett** [comment]
@mheese Sorry, those actually aren't relevant to packaging. I should've made them part of a separate branch. They should definitely be `const`s, though, they should not change!

**Comment by pgaubatz** [comment]
Hi!

@siddharthist Great work! :+1: 

I've just rebased @siddharthist PR onto the current master and added a Debian builder.
FYI this is the changeset https://github.com/pgaubatz/journalbeat/commit/7b60c05bc25dd4e8f950cbe2a4d70b128fd9352d.
If you like, I can submit a PR as well...

Cheers,
Patrick

**Comment by langston-barrett** [comment]
@pgaubatz That'd be great! 

Pinging @mheese

**Comment by pgaubatz** [comment]
@siddharthist Done!

Shall we close this PR?

**Comment by mheese** [comment]
@pgaubatz @siddharthist thanks guys! awesome work 👍

**Pull request closed without merging**
