### PR TITLE
Upgrade to libbeat v6

### PR DESCRIPTION
**Pull request by koesie10**
This is the simplest upgrade to beats v6 with (I believe) the least amount of code changes.

I did have to override some vendored dependencies of elastic/beats to get it to build because dep does not pick up the dependency versions in beats vendor directory.

There are some deprecations in the logp code, which would need to be replaced by a logger in the `Journalbeat` struct, but I wanted to keep this PR as small as possible.

This PR does change the command line interface and the log format, so it is a breaking change.

### CODE REVIEW

**Comment by pontostroy** [comment]
I'm testing for 2 weeks, works fine. Good work.
screenshot_20180917_145017

**Comment by nrvnrvn** [comment]
Hey folks!

@koesie10 thanks for opening up this PR. Sorry for not having time to deal with it. But now seems like I will have some time to look into it finally!

@pontostroy have you encountered any issues with it? I mean the biggest concern in the past was with slow publishing speed and losing of the in-transit messages. Since elastic changed the interface I am a bit anxious if everything is ok after the change. I cannot test it out by myself properly since I'm not using journalbeat anymore and hence cannot run proper performance tests

**Comment by louism517** [comment]
+1 for this

@nrvnrvn We needed beats 6 specifically for the `ttl` function (which is useful when sending to hosts behind a load-balancer). So compiled this from the @koesie10 fork.

We have run some preliminary load tests, each from a single host writing 1000 logs per second to a Logstash output, with 2 configurations:
- with `ttl` set to 10s, and `pipelining` disabled (a pre-req for ttl to have any effect)
- with `pipelining` set to 5. Which means there can be up to 5 batches in flight before Logstash ACKs them.

In both cases we saw no lost messages, and the throughput was equal to a beats 5 version.
Our load testing continues so will update if any problems arise.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html

**Pull request closed without merging**
