### PR TITLE
Add support for arbitrary fields

### PR DESCRIPTION
**Pull request by gmarkey**
Allows configuration of additional arbitrary fields to the output message.

### CODE REVIEW

**Comment by mheese** [comment]
nice! And I thought I have to implement that functionality myself :) ... The PR looks good from what I can see. I will merge it tomorrow in the morning (PST).

**Comment by mheese** [comment]
@gmarkey , I'm going to open another issue for this though: I'd like to see that the destination of the arbitrary fields is configurable.

E.g. let's say I have "fields_dest" set to "fields", then everything is below "fields" like it is now. However, if I leave it empty, all fields are merged into the main map. And if I do "fields.furtherdown", all fields appear below the furtherdown map inside of the fieldsmap.

What do you think?

**Comment by mheese** [comment]
@gmarkey, the latest commit adds a "fields_dest" which can be set to "fields" e.g. It can also receive a nested value (separate with dots).

**Comment by gmarkey** [comment]
@mheese nice :+1:

**Pull request merged**
