### PR TITLE
migrate to dep for dependency management

### PR DESCRIPTION
**Pull request by theRealWardo**
this PR deletes and ignores `vendor` folder and switches to dep for dependency management. when I was hacking on this code, I found dep much easier to use and I believe the Go community is really getting behind it as well.

to build this project now you simply do this:

1. install dep via `go get -u github.com/golang/dep/cmd/dep`
1. `dep ensure`
1. `go build`

### CODE REVIEW

**Comment by nrvnrvn** [comment]
Hi! Thanks for the PR.
A couple of questions:
1. why do you remove the folder containing all the dependencies? (keeping deps in source code is not a crime and does not drag a lot in case of journalbeat)
2. Why is dep better than govendor? (I would rather switch to dep as well for a number of reasons but haven't yet looked at it at all)

**Comment by theRealWardo** [comment]
Thanks @nicorevin for the quick response! as you can tell I'm currently wrestling the build system to get it to work with dep. any pro-tips?

I have no problem with leaving the vendor directory checked in if that is what you prefer, but most projects I've worked on ignore it so that the repo is smaller. this makes it easier to focus on the right thing in pull requests I think. sure it isn't much mental effort to ignore files in vendor, but there is effort. more importantly, with tons of files coming in vendored you might miss a tiny important file if the PR is flooded with files you simply ignore (unless you are actually reviewing vendor code).

I have another change I want to offer which is in the light of #54 and the general community interest in a good logging solution for kubernetes. that change requires a few new dependencies which I was struggling to correctly vendor, so I decided to use dep and with one command (`dep init`) all my problems were solved (and the project was migrated locally at least). I guess I really have liked the simplicity of it compared to alternatives. I've been using dep for my other projects and it has been pretty good so I figured I would try to see if this project was interested in migrating. if not, I'll have to redo my change to work with your current vendoring (not a huge deal I guess).

**Comment by theRealWardo** [comment]
whew. got it working! turns out `/go/bin` is where `dep` ended up after my `go get` call.

🎉

**Comment by nrvnrvn** [comment]
So I've tested out the `dep` tool and can tell the difference between it and `govendor`.
1. `govendor` filters out `_test.go` files and other unnecessary crap except license files. `dep` brings everything.
2. I tend to treat `vendor/` folder as a freezed checked in bundle of dependencies (no matter [how fat it is](https://github.com/kubernetes/kubernetes/tree/master/vendor)). The only drawback is the size of the repo but usually it is not the case unless you start to store some really heavy media inside git itself (instead of leveraging git lfs). As for the benefits: a) you can easily track changes via git diff when updating dependencies, and b) you can skip fetching the deps part in your CI which can be time consuming.
3. The UX of `dep` is on par with `govendor` and this is great.

I would give it a longer try and I would wait for the next minor `elastic/beats` release with fixes for https://github.com/elastic/beats/issues/5131 (which has a workaround in the vendored beats if I'm not mistaken) :)

**Comment by mheese** [comment]
Yeah, that was my understanding as well ;)

I've been using `dep` now since quite some time on a lot of projects and it works great. Specifically: it works in some situations where `govendor` just doesn't (e.g. `kubernetes/client-go` package). `dep` does include tests because it is also running them afaik. A broken dependency will be skipped and not included (when I'm not mistaken). Furthermore it tries to stick to use release versions which I appreciate, and one can deviate from the original source for a package which came in handy already a couple of times.

All in all: I like the idea to move to `dep`, however:
1. I also like to checkin the dependencies (it doesn't hurt, and give you a buildable source code with nothing more than this repo)
2. let's wait for elastic/beats fix that Nico mentioned

**Comment by nrvnrvn** [comment]
@theRealWardo I think we can update beats to [5.6.4](https://www.elastic.co/guide/en/beats/libbeat/5.6/release-notes-5.6.4.html) and merge it down 😃

**Comment by jstoja** [comment]
@theRealWardo @mheese @nicorevin I think it doesn't need much to be merged 👍

**Comment by jstoja** [comment]
@theRealWardo @mheese @nicorevin up ? :)

**Comment by theRealWardo** [comment]
sorry I missed the pings over the holidays! thanks for hitting this up again. updated:

- restored the old vendor directory
- updated to beats 5.6.4 in https://github.com/mheese/journalbeat/pull/125/commits/136e1cd29d7bf337407b0fdfb15b33ec3e9b7d60

let me know if there's any other commits you'd like to see added on here.

**Comment by jstoja** [comment]
looks great to me! I hope @mheese or @nicorevin will merge it soon ! :)

**Comment by theRealWardo** [comment]
hey @mheese or @nicorevin watcha think?

**Comment by theRealWardo** [comment]
friendly little bump @mheese or @nicorevin

**Comment by nrvnrvn** [comment]
Closed in https://github.com/mheese/journalbeat/commit/2799513dd3995f73c60721b868206812c980fdc9

**Pull request closed without merging**
