### PR TITLE
use multi stage build and cleanup

### PR DESCRIPTION
**Pull request by loosi**
I removed the makefile for I dont need it anymore. I would recommend to move over to docker hub build service, thats works well for me even with tags and branches.

### CODE REVIEW

**Comment by jstoja** [comment]
Up on this @mheese ? :)

**Comment by CpuID** [comment]
+1

**Comment by jstoja** [comment]
@CpuID I think we can give up on this repo: https://github.com/mheese/journalbeat/pull/125

**Comment by nrvnrvn** [comment]
Closed via https://github.com/mheese/journalbeat/commit/a9ef82d0c6514d055d5a5b47d9a13fbf330db059

**Pull request closed without merging**
