### PR TITLE
Add option: configurable fields to add on every message

### PR DESCRIPTION
**Pull request by mathpl**
This answer the need for additional data on messages based on the source host's configuration.

### CODE REVIEW

**Comment by CpuID** [comment]
❤️

**Comment by mheese** [comment]
how is this different from what was done in https://github.com/mheese/journalbeat/issues/17 ?

**Comment by mathpl** [comment]
would appear I missed it! Nevermind. :)

**Comment by mheese** [comment]
@mathpl anyway, thanks for the initiative 👍

**Pull request closed without merging**
